services:
  postgresDB:
    image: postgres:latest
    container_name: postgresDB
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: diploma
    volumes:
      - ./data:/var/lib/postgresql/data